/*
 * FightProgressionWindow.java
 *
 * Created on 7 November 2008, 15:04
 */

package au.com.jwatmuff.eventmanager.gui.scoring;

import au.com.jwatmuff.eventmanager.model.vo.Session;
import au.com.jwatmuff.genericdb.Database;
import au.com.jwatmuff.genericdb.transaction.TransactionNotifier;
import java.awt.GridLayout;

/**
 *
 * @author  James
 */
public class FightProgressionWindow extends javax.swing.JFrame {

    private Session matSession;
    private Database database;
    private TransactionNotifier notifier;
    private FightProgressionPanel fightProgressionPanel, fullScreenPanel;
    private ScoringColors colors = new ScoringColors();

    /** Creates new form FightProgressionWindow */
    public FightProgressionWindow(Database database, TransactionNotifier notifier, Session mat) {
        initComponents();
        setLocationRelativeTo(null);
        this.matSession = mat;
        this.database = database;
        this.notifier = notifier;

        fightProgressionPanel = getFightProgressionPanel();
        fullScreenPanel = getFightProgressionPanel();
        fightProgressionPanel.setColors(colors);
        fullScreenPanel.setColors(colors);

        getContentPane().setLayout(new GridLayout(1,1));
        getContentPane().add(fightProgressionPanel);
        setTitle("Event Manager - Fight Progression - [" + mat.getMat() + "]");
    }
    
    private FightProgressionPanel getFightProgressionPanel() {
        FightProgressionPanel fpp = new FightProgressionPanel(matSession);
        fpp.setDatabase(database);
        fpp.setNotifier(notifier);
        fpp.setParentWindow(this);
        fpp.afterPropertiesSet();
        return fpp;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
