/*
 * PanelDisplayFrame.java
 *
 * Created on 5 September 2008, 17:27
 */

package au.com.jwatmuff.eventmanager.util.gui;

import java.awt.Container;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author  James
 */
public class PanelDisplayFrame extends javax.swing.JFrame {

    /** Creates new form PanelDisplayFrame */
    public PanelDisplayFrame(JPanel content) {
        super();
        //initComponents();
        Container c = getContentPane();
        c.setLayout(new GridLayout(1,1));
        c.add(content);
        pack();
        this.setLocationByPlatform(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
