/*
 * ChatPanel.java
 *
 * Created on 18 April 2008, 23:32
 */

package au.com.jwatmuff.eventmanager.gui.main;

import au.com.jwatmuff.eventmanager.p2p.chat.ChatService;
import au.com.jwatmuff.genericp2p.Peer;
import au.com.jwatmuff.genericp2p.PeerConnectionEvent;
import au.com.jwatmuff.genericp2p.PeerConnectionListener;
import au.com.jwatmuff.genericp2p.PeerManager;
import foxtrot.Job;
import foxtrot.Worker;
import java.util.Date;
import java.util.Vector;
import javax.swing.SwingUtilities;
import org.apache.log4j.Logger;

/**
 *
 * @author  James
 */
public class ChatPanel extends javax.swing.JPanel {
    private static final Logger log = Logger.getLogger(ChatPanel.class);

    private PeerManager peerManager;
    
    /** Creates new form ChatPanel */
    public ChatPanel(final PeerManager peerManager) {
        initComponents();
    
        this.peerManager = peerManager;
        peerManager.addConnectionListener(new PeerConnectionListener() {
            @Override
            public void handleConnectionEvent(PeerConnectionEvent event) {
                updateUserList();
                appendToChat("NETWORK", "Peer " + event.getPeer().getName() + " " + event.getType() + " at " + new Date() + "\n-------------");
            }
        });
        updateUserList();
        
        peerManager.registerService(ChatService.class, new ChatService() {
            @Override
            public void sendMessage(String message, String fromPeer) {
                handleMessage(message, fromPeer);
            }
        });
    }
    
    @SuppressWarnings("UseOfObsoleteCollectionType")
    private void updateUserList() {
        userList.setListData(new Vector<Peer>(peerManager.getPeers()));
    }

    private void appendToChat(String source, String message) {
        chatTextPane.setText(chatTextPane.getText() + "[" + source + "]: " + message + "\n");
    }

    public void handleMessage(final String message, final String fromPeer) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                chatTextPane.setText(chatTextPane.getText() + "[" + fromPeer + "]: " + message + "\n");
            }
        });
    }
    
    public void sendMessage() {
        Worker.post(new Job() {
            @Override
            public Object run() {
                String message = chatEntryTextField.getText();

                if(message.trim().length() == 0)
                    return null;

                chatEntryTextField.setText("");
                //chatTextPane.setText(chatTextPane.getText() + "[You]: " + message + "\n");

                for(Peer peer : peerManager.getPeers()) {
                    try {
                        peer.getService(ChatService.class).sendMessage(message, System.getProperty("user.name"));
                    } catch(Exception e) {
                        log.error("Error while sending message to peer '" + peer.getName() + "'", e);
                    }
                }
                return null;
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<Peer>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatTextPane = new javax.swing.JTextPane();
        chatEntryTextField = new javax.swing.JTextField();
        sayButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(userList);

        jLabel1.setText("Users online");

        chatTextPane.setEditable(false);
        jScrollPane2.setViewportView(chatTextPane);

        chatEntryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatEntryTextFieldActionPerformed(evt);
            }
        });

        sayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/famfamfam/icons/silk/comment.png"))); // NOI18N
        sayButton.setText("Say");
        sayButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        sayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sayButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Chat");

        jLabel3.setText("Messages");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chatEntryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sayButton))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sayButton)
                    .addComponent(chatEntryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chatEntryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatEntryTextFieldActionPerformed
        sendMessage();
    }//GEN-LAST:event_chatEntryTextFieldActionPerformed

    private void sayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sayButtonActionPerformed
        sendMessage();
    }//GEN-LAST:event_sayButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatEntryTextField;
    private javax.swing.JTextPane chatTextPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sayButton;
    private javax.swing.JList<Peer> userList;
    // End of variables declaration//GEN-END:variables
    
}
