/*
 * LoadCompetitionWindow.java
 *
 * Created on 23 July 2008, 13:26
 */

package au.com.jwatmuff.eventmanager.gui.main;

import au.com.jwatmuff.eventmanager.gui.license.LicenseKeyDialog;
import au.com.jwatmuff.eventmanager.permissions.License;
import au.com.jwatmuff.eventmanager.permissions.LicenseManager;
import au.com.jwatmuff.eventmanager.util.GUIUtils;
import au.com.jwatmuff.genericdb.p2p.DatabaseInfo;
import au.com.jwatmuff.genericdb.p2p.DatabaseManager;
import java.awt.Component;
import java.io.IOException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.SwingUtilities;
import org.apache.log4j.Logger;

/**
 * This interface is the entry point to the EventManager program. It lists
 * all local and network competition databases, allowing the user to launch
 * the EventManager for one of these competitions or a brand new competition.
 *
 * @author  James
 */
public class LoadCompetitionWindow extends javax.swing.JFrame {
    private static Logger log = Logger.getLogger(LoadCompetitionWindow.class);
    
    private DatabaseManager dbManager;
    private LicenseManager licenseManager;
    
    private DatabaseInfo selected;
    private boolean isNew = false;
    private boolean success = false;
    
    private DefaultListModel dbListModel = new DefaultListModel();
    
    /** Creates new form LoadCompetitionWindow */
    public LoadCompetitionWindow(DatabaseManager dbManager, LicenseManager licenseManager) {
        initComponents();
        setIconImage(Icons.MAIN_WINDOW.getImage());

        this.dbManager = dbManager;
        this.licenseManager = licenseManager;
        this.getRootPane().setDefaultButton(okButton);

        competitionList.setCellRenderer(new DefaultListCellRenderer() {
            private ImageIcon localIcon = new ImageIcon(getClass().getResource("/com/famfamfam/icons/silk/drive.png"));
            private ImageIcon remoteIcon = new ImageIcon(getClass().getResource("/com/famfamfam/icons/silk/transmit.png"));

            @Override
            public Component getListCellRendererComponent(JList list, Object obj, int arg2, boolean arg3, boolean arg4) {
                if(obj instanceof DatabaseInfo) {
                    DatabaseInfo di = (DatabaseInfo)obj;
                    JLabel label = (JLabel)super.getListCellRendererComponent(list, di.name, arg2, arg3, arg4);
                    label.setIcon(di.local?localIcon:remoteIcon);
                    return label;
                }
                return super.getListCellRendererComponent(list, obj, arg2, arg3, arg4);
            }
            
        });
        
        this.competitionList.setModel(dbListModel);        
        updateDatabaseList();
        updateLicenseInfo();
        
        dbManager.setListener(new DatabaseManager.Listener() {
            @Override
            public void handleDatabaseManagerEvent() {                
                updateDatabaseList();
            }
        });
        
        // center window on screen
        setLocationRelativeTo(null);
    }
    
    private void updateDatabaseList() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                dbListModel.clear();
                for(DatabaseInfo info : dbManager.getDatabases())
                    dbListModel.addElement(info);
                
                boolean compsPresent = dbListModel.size() > 0;
                existingCompRadioButton.setEnabled(compsPresent);
            }
        });   
    }

    private void updateLicenseInfo() {
        License license = licenseManager.getLicense();

        if(license == null) {
            licenseNameLabel.setText("N/A");
            licenseContactLabel.setText("N/A");
            licenseTypeLabel.setText("FREE");
            licenseExpiryLabel.setText("Never");
        } else {
            licenseNameLabel.setText(license.getName());
            licenseContactLabel.setText(license.getContactPhoneNumber());
            licenseTypeLabel.setText(license.getType().toString());
            licenseExpiryLabel.setText(license.getExpiry().toString());
        }
        this.pack();
    }
    
    public boolean getSuccess() {
        return success;
    }
    
    public DatabaseInfo getSelectedDatabaseInfo() {
        return selected;
    }
    
    public boolean isNewDatabase() {
        return isNew;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        existingCompRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        competitionList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        newCompRadioButton = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        licenseNameLabel = new javax.swing.JLabel();
        licenseContactLabel = new javax.swing.JLabel();
        licenseTypeLabel = new javax.swing.JLabel();
        licenseExpiryLabel = new javax.swing.JLabel();
        loadLicenseButton = new javax.swing.JButton();
        enterLicenseKeyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Event Manager");
        setLocationByPlatform(true);
        setResizable(false);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(existingCompRadioButton);
        existingCompRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        existingCompRadioButton.setText("Load Existing Competition");
        existingCompRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        existingCompRadioButton.setEnabled(false);
        existingCompRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        competitionList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        competitionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                competitionListMouseClicked(evt);
            }
        });
        competitionList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                competitionListFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(competitionList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(existingCompRadioButton))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existingCompRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(newCompRadioButton);
        newCompRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newCompRadioButton.setSelected(true);
        newCompRadioButton.setText("Create New Competition");
        newCompRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        newCompRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCompRadioButton)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCompRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Start Competition", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Manual Interfaces *", jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Current License"));

        jLabel1.setText("Name:");

        jLabel2.setText("Contact Phone:");

        jLabel3.setText("Level:");

        jLabel4.setText("Expiry:");

        licenseNameLabel.setText("N/A");

        licenseContactLabel.setText("N/A");

        licenseTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        licenseTypeLabel.setText("FREE");

        licenseExpiryLabel.setText("N/A");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(licenseNameLabel))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(licenseContactLabel))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(licenseTypeLabel))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(licenseExpiryLabel)))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(licenseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(licenseContactLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(licenseTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(licenseExpiryLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loadLicenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/famfamfam/icons/silk/key_add.png"))); // NOI18N
        loadLicenseButton.setText("Load License File..");
        loadLicenseButton.setIconTextGap(8);

        enterLicenseKeyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/famfamfam/icons/silk/key_add.png"))); // NOI18N
        enterLicenseKeyButton.setText("Enter License Key..");
        enterLicenseKeyButton.setIconTextGap(8);
        enterLicenseKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLicenseKeyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(loadLicenseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterLicenseKeyButton)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadLicenseButton)
                    .addComponent(enterLicenseKeyButton))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Licenses", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void competitionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_competitionListMouseClicked
        // handle double click on a list the same as pressing OK
        if(evt.getClickCount() == 2 && existingCompRadioButton.isSelected())
            okButtonActionPerformed(null);
}//GEN-LAST:event_competitionListMouseClicked
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(newCompRadioButton.isSelected()) {
            NewCompetitionDialog ncd = new NewCompetitionDialog(this, true);
            ncd.setVisible(true);
            if(ncd.getSuccess()) {
                selected = dbManager.createNewDatabase(ncd.getCompetitionName(), ncd.getPasswordHash());
                isNew = true;
                success = true;
                this.dispose();
                return;
            }
        }
        
        if(existingCompRadioButton.isSelected()) {
            selected = (DatabaseInfo)competitionList.getSelectedValue();
            if(selected == null) return;
            /*
             * TODO: check password
             * 
            if(!selected.local || selected.passwordHash != 0) {
                EnterPasswordDialog epd = new EnterPasswordDialog();
                epd.setVisible(true);
                if(epd.getSuccess()) {
                    
                }
            }
             */
            success = true;
            this.dispose();
            return;
        }
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void competitionListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_competitionListFocusGained
        if(existingCompRadioButton.isEnabled())
            existingCompRadioButton.setSelected(true);
}//GEN-LAST:event_competitionListFocusGained

    private void enterLicenseKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLicenseKeyButtonActionPerformed
        LicenseKeyDialog dialog = new LicenseKeyDialog(null, true);
        dialog.setVisible(true);
        if(dialog.getSuccess()) {
            try {
                licenseManager.setLicense(dialog.getLicense());
            } catch(IOException e) {
                GUIUtils.displayError(null, "Unable to save license file. License will not be remembered after EventManager is closed");
            }
            updateLicenseInfo();
        }
    }//GEN-LAST:event_enterLicenseKeyButtonActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JList competitionList;
    private javax.swing.JButton enterLicenseKeyButton;
    private javax.swing.JRadioButton existingCompRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel licenseContactLabel;
    private javax.swing.JLabel licenseExpiryLabel;
    private javax.swing.JLabel licenseNameLabel;
    private javax.swing.JLabel licenseTypeLabel;
    private javax.swing.JButton loadLicenseButton;
    private javax.swing.JRadioButton newCompRadioButton;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
