/*
 * LoadCompetitionWindow.java
 *
 * Created on 23 July 2008, 13:26
 */

package au.com.jwatmuff.eventmanager.gui.main;

import au.com.jwatmuff.eventmanager.gui.admin.EnterPasswordDialog;
import au.com.jwatmuff.genericdb.p2p.DatabaseInfo;
import au.com.jwatmuff.genericdb.p2p.DatabaseManager;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.SwingUtilities;
import org.apache.log4j.Logger;

/**
 * This interface is the entry point to the EventManager software. It lists
 * all local and network competition databases, allowing the user to launch
 * the EventManager for one of these competitions or a brand new competition.
 *
 * @author  James
 */
public class LoadCompetitionWindow extends javax.swing.JFrame {
    private static Logger log = Logger.getLogger(LoadCompetitionWindow.class);
    
    private DatabaseManager dbManager;
    
    private DatabaseInfo selected;
    private boolean isNew = false;
    private boolean success = false;
    
    private DefaultListModel dbListModel = new DefaultListModel();
    
    /** Creates new form LoadCompetitionWindow */
    public LoadCompetitionWindow(DatabaseManager dbManager) {
        initComponents();
        setIconImage(Icons.MAIN_WINDOW.getImage());

        this.dbManager = dbManager;
        this.getRootPane().setDefaultButton(okButton);

        competitionList.setCellRenderer(new DefaultListCellRenderer() {
            private ImageIcon localIcon = new ImageIcon(getClass().getResource("/com/famfamfam/icons/silk/drive.png"));
            private ImageIcon remoteIcon = new ImageIcon(getClass().getResource("/com/famfamfam/icons/silk/transmit.png"));

            @Override
            public Component getListCellRendererComponent(JList list, Object obj, int arg2, boolean arg3, boolean arg4) {
                if(obj instanceof DatabaseInfo) {
                    DatabaseInfo di = (DatabaseInfo)obj;
                    JLabel label = (JLabel)super.getListCellRendererComponent(list, di.name, arg2, arg3, arg4);
                    label.setIcon(di.local?localIcon:remoteIcon);
                    return label;
                }
                return super.getListCellRendererComponent(list, obj, arg2, arg3, arg4);
            }
            
        });
        
        this.competitionList.setModel(dbListModel);        
        updateDatabaseList();
        
        dbManager.setListener(new DatabaseManager.Listener() {
            @Override
            public void handleDatabaseManagerEvent() {                
                updateDatabaseList();
            }
        });
        
        // center window on screen
        setLocationRelativeTo(null);
    }
    
    private void updateDatabaseList() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                dbListModel.clear();
                for(DatabaseInfo info : dbManager.getDatabases())
                    dbListModel.addElement(info);
                
                boolean compsPresent = dbListModel.size() > 0;
                existingCompRadioButton.setEnabled(compsPresent);
            }
        });   
    }
    
    public boolean getSuccess() {
        return success;
    }
    
    public DatabaseInfo getSelectedDatabaseInfo() {
        return selected;
    }
    
    public boolean isNewDatabase() {
        return isNew;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        newCompRadioButton = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        existingCompRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        competitionList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Event Manager");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(newCompRadioButton);
        newCompRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        newCompRadioButton.setSelected(true);
        newCompRadioButton.setText("Create New Competition");
        newCompRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        newCompRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCompRadioButton)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCompRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(existingCompRadioButton);
        existingCompRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        existingCompRadioButton.setText("Load Existing Competition");
        existingCompRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        existingCompRadioButton.setEnabled(false);
        existingCompRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        competitionList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        competitionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                competitionListMouseClicked(evt);
            }
        });
        competitionList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                competitionListFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(competitionList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addComponent(existingCompRadioButton))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existingCompRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(okButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelButton))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void competitionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_competitionListMouseClicked
        // handle double click on a list the same as pressing OK
        if(evt.getClickCount() == 2 && existingCompRadioButton.isSelected())
            okButtonActionPerformed(null);
}//GEN-LAST:event_competitionListMouseClicked
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if(newCompRadioButton.isSelected()) {
            NewCompetitionDialog ncd = new NewCompetitionDialog(this, true);
            ncd.setVisible(true);
            if(ncd.getSuccess()) {
                selected = dbManager.createNewDatabase(ncd.getCompetitionName(), ncd.getPasswordHash());
                isNew = true;
                success = true;
                this.dispose();
                return;
            }
        }
        
        if(existingCompRadioButton.isSelected()) {
            selected = (DatabaseInfo)competitionList.getSelectedValue();
            if(selected == null) return;
            /*
             * TODO: check password
             * 
            if(!selected.local || selected.passwordHash != 0) {
                EnterPasswordDialog epd = new EnterPasswordDialog();
                epd.setVisible(true);
                if(epd.getSuccess()) {
                    
                }
            }
             */
            success = true;
            this.dispose();
            return;
        }
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void competitionListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_competitionListFocusGained
        if(existingCompRadioButton.isEnabled())
            existingCompRadioButton.setSelected(true);
}//GEN-LAST:event_competitionListFocusGained
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JList competitionList;
    private javax.swing.JRadioButton existingCompRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton newCompRadioButton;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
